### PR TITLE
adding additional filters for endpoints

### PR DESCRIPTION
**Pull request by mrantipyrine**
## Description
Adding additional filters for vpc endpoints to resolve SRE-1509

## Motivation and Context
Should resolve the following error when running plans against all accounts for the vpc-main module.

"multiple VPC Endpoint Services matched; use additional constraints to reduce matches to a single VPC Endpoint Service"

https://jenkins.zefr.com/job/SRE-Builder/job/terraform-infrastructure-new-home/job/master/1833/console

### CODE REVIEW

**Review by kencieszykowski — COMMENTED** [review]
LGTM

**Comment by lukaalex** [comment]
@mrantipyrine can you link the jenkins job for terraform-infrastructure-new-home where it passes? I'm not seeing a passing run there.

**Comment by mrantipyrine** [comment]
> @mrantipyrine can you link the jenkins job for terraform-infrastructure-new-home where it passes? I'm not seeing a passing run there.

https://jenkins.zefr.com/job/SRE-Builder/job/terraform-infrastructure-new-home/view/change-requests/job/PR-472/8/console 

Just got it to plan without error.

**Comment by lukaalex** [comment]
> https://jenkins.zefr.com/job/SRE-Builder/job/terraform-infrastructure-new-home/view/change-requests/job/PR-472/8/console

That jenkins run is for `iam-jenkins`, we need to plan against `vpc-main`

**Pull request closed without merging**
